### ISSUE TITLE
Will oboe work with a stream of json objects?

### ISSUE THREAD

**Issue by kevinday** [jimhigson/oboe.js#115]
I have an express server that is streaming json objects like so
```
app.get('/getJsonObjects', function (req, res) {
    res.write(JSON.stringify(json1));
    res.write(JSON.stringify(json2));
    res.write(JSON.stringify(json3));
    res.write(JSON.stringify(json4));
    res.write(JSON.stringify(json5));
    res.end();
});
```
On the client side, I'm trying to consume each chunk like
```
var r = request(url);
r.on('data', function(data) {
    console.log(JSON.parse(data));
});
```
The problem is despite streaming to the endpoint chunks of valid stringified JSON, the chunks I'm getting back from the request are just text chunks that don't necessarily align with the start/end of the JSON chunks that were sent from the server. This means that JSON.parse(data) will sometimes fail.

Is this a good fit for oboe? Is oboe able to recognize the start/end of json objects streamed from an http endpoint, and emit an event for each object it detects accordingly?

An example of an endpoint I'm trying to consume is here:
`http://augurnode1.eastus.cloudapp.azure.com:8547/getMarketsInfo?branchId=eq,1010101`

**Comment by RonB** [comment]
Should work Just fine.....

Op wo 7 sep. 2016 02:10 schreef kevinday <notifications@github.com>:

**Comment by JuanCaicedo** [comment]
I would have two concerns with your end point.

One is that I don't know if `res.write` is synchronous. If it's asynchronous, it's possible you'll have multiple calls writing out to the response at the same time, and therefore getting mixed together. 

The other is that the response your endpoint will send will be a string of non-separated objects. I would start out by writing `\n` after each one, to see if that works. However, [I'm not sure it will](https://github.com/jimhigson/oboe.js/issues/63). The other solution is to start your response with `[`, end it with `]`, and put a `,` between each object. 

Oboe should work fine for what you need though if you're able to make a normal REST call to that endpoint and get valid data.  If you check through the [docs](http://www.oboejs.com/examples) you should be able to get an idea of how to use it. [This video](https://skillsmatter.com/skillscasts/8160-better-json-through-streams) from a talk I gave might be helpful. (You'll have to make an account to view, but it's free).

Closing this since it's not really an issue
