### ISSUE TITLE
oboe.drop doesn't free memory in my case

### ISSUE THREAD

**Issue by cschwaderer** [jimhigson/oboe.js#154]
Hi all,

I came across oboe recently and my first impression was pretty much positive! I really like how smooth it works. Then, however, I used bigger datasets and my browser began to crash.
Obviously, there is a memory problem with oboe.

This is how my code looks right now:

```
var myOboeObject = oboe({
            url: '/someURL/',
            method: 'POST',
            headers: {
                authorization: { /* .... */ }
            },
            body: { /* .... */ }
        });

        var myfooArray = [];
        myOboeObject.on('node','{some_property_which_is_everwhere_there}',function(node) {
            myfooArray.push(node);
            return oboe.drop;
        });
```

The problem seems to be that `oboe.drop` doesn't work as expected for me. It seems to work if there I don't do anything with the `node` parameter. Then the memory gets freed immediately and there is no problem in the browser.

However, as soon the `node` parameter is used somehow (even a `console.log` or just using one property of it or even copying it with `angular.copy`) the memory is not freed and eventually, the browser will crash.

See image attached:

![oboe_mem1](https://user-images.githubusercontent.com/18464127/34150237-155d20ec-e4a8-11e7-9661-a4a381b9981e.png)

Am I doing something wrong? Or is this a problem of oboe?
I'm a little bit desparate right now because I cannot have browser crashes, even very much lower performance is better than crashes because of too much memory used.

**Comment by JuanCaicedo** [comment]
@cschwaderer I'm sorry to hear that, it sounds really frustrating! Unfortunately I'm not sure what's going wrong, from my understanding that's exactly how `oboe.drop` should work. You could try using `oboe({...}).node` instead of `.on('node')` to see if that makes a difference. Sorry!

**Comment by tsouza** [comment]
@cschwaderer maybe you could try https://github.com/tsouza/yajs . It has a different set of features then oboe, but maybe it is enough for you. The good thing is that it doesn't have the memory issues that you have mentioned here (check https://github.com/tsouza/yajs/blob/master/benchmark.md).

The target of the library is nodejs, but I think it should be straightforward so it works in a browser too.

**Comment by adamhooper** [comment]
I think I've experienced this with Oboe myself. And I have a guess as to why.

My assumptions:

1. XMLHttpRequest's `responseText` keeps changing to new locations in memory as the download progresses. (This must be the case, right? I'm using `Transfer-Encoding: chunked`, which means the browser doesn't have enough knowledge to pre-allocate a correctly-sized String. And I need to use `chunked`, because if I knew the `Content-Length` ahead of time I wouldn't need Oboe in the first place :).)
2. The Strings Oboe pipes to me are substrings of `responseText`.
3. Substrings reference the original string.
4. My stream is taking a long time to come -- meaning many chunks.

My hypothesis: if you store even one single-character String from a JSON object Oboe passes, that single-character String actually references the _entire_ `responseText`, meaning it can't be garbage-collected. Oboe itself isn't holding a reference to `responseText`, so `oboe.drop` doesn't free memory. The _caller_ is holding the reference.

I've seen the same behavior in Node with https://github.com/cheeriojs/cheerio/issues/263 -- the underlying issue is https://code.google.com/p/v8/issues/detail?id=2869 and it's unlikely to change soon.

If this is indeed the problem that's causing abundant memory usage, the solution is to ... er ... "copy" each substring Oboe returns. That way you'll only reference the (small) _copy_, not the (large) `responseText`. A sample `copy` function:

```javascript
function copyString(substringOfHugeString) {
  return (' ' + substringOfHugeString).substr(1);
}
```

If you only store the return values from `copyString()` and never the direct Strings from Oboe, _and if I'm right_, then the memory problems should go away.

Another way to mitigate the problem would be to build a `fetch`-based HTTP transport. Since `fetch` does actual streaming -- instead of building bigger and bigger `responseText` Strings -- callers wouldn't be able to refer to more memory than the total size of the HTTP response.

Oboe devs: am I way off base? Or does this sound like a viable diagnosis?

**Comment by willkara** [comment]
Can recreate this myself. I'm parsing a large JSON document from the web and even though I end the **.node** block with return oboe.drop, the memory usage continues to climb.

**Comment by mrft** [comment]
Small report of what I experienced:

```javascript
oboe( myReadStream )
 .node('results.*', r => {
    let doc = r.doc
    // do your stuff
    return oboe.drop
 } )
```

works and properly releases the memory, but

```javascript
oboe( myReadStream )
    .node('results.*.doc', doc => {
    // do your stuff
     return oboe.drop
 } )
```
doesn't release the memory...

**Comment by Aigeec** [comment]
This appears to be an issue with the original clarinet code. @adamhooper is somewhat correct. It does not appear to be the responseText but rather the chunks that are being kept.

Applying the `(' ' + substringOfHugeString).substr(1);` fix to the following lines resolved the issue and greatly reduces the memory used:
[L340](https://github.com/jimhigson/oboe.js/blob/295d6305776798ac6222a45f3ea9a4df947c640e/src/libs/clarinet.js#L340)
[L345](https://github.com/jimhigson/oboe.js/blob/295d6305776798ac6222a45f3ea9a4df947c640e/src/libs/clarinet.js#L345)
[L373](https://github.com/jimhigson/oboe.js/blob/295d6305776798ac6222a45f3ea9a4df947c640e/src/libs/clarinet.js#L373)
[L379](https://github.com/jimhigson/oboe.js/blob/295d6305776798ac6222a45f3ea9a4df947c640e/src/libs/clarinet.js#L379)

I will create a PR tomorrow for this, will need to figure out how to test it.

**Comment by willkara** [comment]
@Aigeec Let me know if I can help testing. I'm thinking you run it through a few test cases of parsing large JSON streams. I know a few endpoints you can use to test it.

**Comment by Aigeec** [comment]
@adamhooper was correct in that we are referencing the responseText. I moved the fix up to where we are substringing from the responseText and the issue was resolved. There maybe some scenarios where the substring in the clarinet code is done but mostly its probably not necessary.
