### ISSUE TITLE
Support for jsonl

### ISSUE THREAD

**Issue by adius** [jimhigson/oboe.js#63]
It would be cool if oboe supported json lines streams.
http://jsonlines.org/

**Comment by goloroden** [comment]
+1

**Comment by ooxi** [comment]
If I understand JSON Lines correctly, it's just JSON with the convention to separate each character with a line separator. Thus oboe.js can already read the JSON subset JSON Lines.

**Comment by derekperkins** [comment]
:+1:

**Comment by derekperkins** [comment]
@adius / @goloroden - How are you handling jsonl now while oboe.js doesn't support it yet?

**Comment by goloroden** [comment]
We have written our own modules for that: [json-lines](https://github.com/thenativeweb/json-lines) and [json-lines-client](https://github.com/thenativeweb/json-lines-client)

**Comment by tannerlinsley** [comment]
How do they perform compared to other methods of parsing?

**Comment by goloroden** [comment]
At least they [don't produce memory leaks](https://github.com/jimhigson/oboe.js/issues/68) ;-)

Okay, to be serious, we have not measured it so far.
For us, it has been okay.

**Comment by JuanCaicedo** [comment]
I know I'm about a year late to this discussion, but I think this might already be possible with oboe, unless I'm misunderstanding what jsonl is. 

The `!` pattern will be matched when the root object is parsed. A jsonl response will have many root objects, but each should trigger this pattern you can check this out [on this hyperdev](https://square-gem.hyperdev.space/) I made and view the souce [here](https://hyperdev.com/#!/project/square-gem). 

Let me know if this doesn't address this issue, otherwise I will close it in a few days 😃
