### ISSUE TITLE
.done and .fail are both called on error response with payload

### ISSUE THREAD

**Issue by levibotelho** [jimhigson/oboe.js#64]
When receiving an error response with a payload, oboe fires the `done` callback, followed by the `fail` callback.

This is the response I'm receiving:

```
HTTP/1.1 401 Unauthorized
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Mon, 06 Apr 2015 09:13:01 GMT

{"code":1,"message":"Invalid credentials"}
```

The `done` method fires first and is passed the parsed JSON response object. The `fail` method fires shortly thereafter with the statusCode correctly set.

Unless I'm mistaken, `done` should not be fired here because the response contains an error. This is what happens when the webserver returns just an error code with no JSON response.

**Comment by pixeleet** [comment]
+1 Exactly mi issue and use case.

**Comment by pixeleet** [comment]
Okay so I did a bit of digging, and here's what's happening.

This piece here correctly detects
https://github.com/jimhigson/oboe.js/blob/master/src/streamingHttp.browser.js#L74-L118

While this piece totally ignores if you have a successful request or not, will stream the json response and call done when the stream ends.
https://github.com/jimhigson/oboe.js/blob/master/src/streamingHttp.browser.js#L50-L67

So in the end a done event is fired when the stream is parsed. 
Then fails is fired, because the request was unsuccessful. 

If you only stream successful requests, then only error is emitted on error, as per the readystate change handler. Handle progress should ignore a failed request. I guess ;) :8ball: 

Use at your own risk.
``` js
function handleProgress() {

     if (String(xhr.status)[0] == 2) {
       
        var textSoFar = xhr.responseText,
            newText = textSoFar.substr(numberOfCharsAlreadyGivenToCallback);

        /* Raise the event for new text.

           On older browsers, the new text is the whole response.
           On newer/better ones, the fragment part that we got since
           last progress. */

        if( newText ) {
           emitStreamData( newText );
        }

        numberOfCharsAlreadyGivenToCallback = len(textSoFar);
      }
   }
```

**Comment by aldipower** [comment]
+1

**Comment by pixeleet** [comment]
@jimhigson any update?

**Comment by anasanzari** [comment]
any update?
